# PURL configuration for http://purl.obolibrary.org/obo/chebi

idspace: CHEBI
base_url: /obo/chebi

products:
- chebi.owl: ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl
- chebi.obo: ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.obo
- chebi.owl.gz: ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl.gz
- chebi.obo.gz: ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.obo.gz

term_browser: custom

entries:
- exact: /tracker
  replacement: https://github.com/ebi-chebi/ChEBI/issues

- exact: /browse
  replacement: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A24431

- exact: /internal/chebi-disjoints.owl
  replacement: ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi-disjoints.owl

- exact: /internal/chebi-in-bfo.owl
  replacement: ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi-in-bfo.owl

- exact: /internal/chebi.owl
  replacement: ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl

- prefix: /about/
  replacement: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=
  tests:
  - from: /about/CHEBI_15377
    to: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI_15377

