# PURL configuration for http://purl.obolibrary.org/obo/clo

idspace: CLO
base_url: /obo/clo

products:
- clo.owl: https://raw.githubusercontent.com/ICO-ontology/ICO/master/ico.owl

term_browser: ontobee
example_terms:
- CLO_0000001
- CLO_0000031
- CLO_0003684
