# PURL configuration for http://purl.obolibrary.org/obo/ddanat

idspace: DDANAT
base_url: /obo/ddanat

products:
- ddanat.owl: http://ontologies.berkeleybop.org/ddanat.owl

term_browser: ontobee
example_terms:
- DDANAT_0000002
