# PURL configuration for http://purl.obolibrary.org/obo/doid

idspace: DOID
base_url: /obo/doid

base_redirect: https://github.com/DiseaseOntology/HumanDiseaseOntology/tree/master/

products:
- doid.owl: https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/doid.owl
- doid.obo: https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/doid-non-classified.obo

term_browser: ontobee
example_terms:
- DOID_4

entries:

- exact: /obo/ext.owl
  replacement: https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/ext.owl

- prefix: /imports/
  replacement: https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/imports/
  tests:
  - from: /imports/relations.owl
    to: https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/imports/relations.owl

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/releases/
  tests:
  - from: /releases/2017-01-27/doid.owl
    to: https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/releases/2017-01-27/doid.owl
