# PURL configuration for http://purl.obolibrary.org/obo/doid

idspace: DOID
base_url: /obo/doid

base_redirect: https://github.com/DiseaseOntology/HumanDiseaseOntology/tree/master/

products:
- doid.owl: https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/doid.owl
- doid.obo: https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/doid.obo

term_browser: ontobee
example_terms:
- DOID_4
