# PURL configuration for http://purl.obolibrary.org/obo/dron

idspace: DRON
base_url: /obo/dron

products:
- dron.owl: https://github.com/ufbmi/dron/releases/latest/download/dron.owl
- dron.obo: https://github.com/ufbmi/dron/releases/latest/download/dron.obo
- dron.json: https://github.com/ufbmi/dron/releases/latest/download/dron.json

term_browser: ontobee
example_terms:
- DRON_00010000

entries:
- exact: /dev/dron-rxnorm.owl
  replacement: https://s3.amazonaws.com/drugontology/dev/dron-rxnorm.owl

- exact: /dev/dron-ndc.owl
  replacement: https://s3.amazonaws.com/drugontology/dev/dron-ndc.owl

- exact: /dron-ndc.owl
  replacement: https://s3.amazonaws.com/drugontology/dron-ndc.owl

- exact: /dron-rxnorm.owl
  replacement: https://s3.amazonaws.com/drugontology/dron-rxnorm.owl

- exact: /dron-ingredient.owl
  replacement: https://s3.amazonaws.com/drugontology/dron-ingredient.owl

- exact: /dev/dron-ingredient.owl
  replacement: https://s3.amazonaws.com/drugontology/dev/dron-ingredient.owl

- prefix: /releases/
  replacement: https://github.com/ufbmi/dron/releases/download/v
  tests:  
    - from: /releases/2021-08-12/dron-base.obo
      to: https://github.com/ufbmi/dron/releases/download/v2021-08-12/dron-base.obo

- prefix: /
  replacement: https://github.com/ufbmi/dron/releases/latest/download/
  tests:  
    - from: /dron-base.json
      to: https://github.com/ufbmi/dron/releases/latest/download/dron-base.json

