# PURL configuration for http://purl.obolibrary.org/obo/duo

idspace: DUO
base_url: /obo/duo

products:
- duo.owl: https://raw.githubusercontent.com/EBISPOT/DUO/master/duo.owl
- duo.obo: https://raw.githubusercontent.com/EBISPOT/DUO/master/duo.obo
- duo.csv: https://raw.githubusercontent.com/EBISPOT/DUO/master/duo.csv

term_browser: custom
example_terms:
- DUO_0000000

entries:

- prefix: /home/
  replacement: https://github.com/EBISPOT/DUO
  
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/EBISPOT/DUO/v

- prefix: /tracker/
  replacement: https://github.com/EBISPOT/DUO/issues

- prefix: /about/
  replacement: https://www.ebi.ac.uk/ols/ontologies/duo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/EBISPOT/DUO/master/
