# PURL configuration for http://purl.obolibrary.org/obo/eupath

idspace: EUPATH
base_url: /obo/eupath

products:
- eupath.owl: https://raw.githubusercontent.com/EuPath-ontology/EuPath-ontology/2018-05-09/ontology/src/eupath.owl

term_browser: ontobee
example_terms:
- EUPATH_0000001

entries:
- exact: /2018-05-09/obib.owl
  replacement: https://raw.githubusercontent.com/EuPath-ontology/EuPath-ontology/2018-05-09/ontology/src/eupath.owl
