# PURL configuration for http://purl.obolibrary.org/obo/exo

idspace: ExO
base_url: /obo/exo

products:
- exo.owl: http://ontologies.berkeleybop.org/exo.owl

term_browser: ontobee
example_terms:
- ExO_0000000
