# PURL configuration for http://purl.obolibrary.org/obo/fbbi

idspace: FBbi
base_url: /obo/fbbi

products:
- fbbi.owl: http://ontologies.berkeleybop.org/fbbi.owl

term_browser: ontobee
example_terms:
- FBbi_0000001
