# PURL configuration for http://purl.obolibrary.org/obo/go

idspace: GO
base_url: /obo/go

products:
- go.owl: http://geneontology.org/ontology/go.owl
- go.obo: http://geneontology.org/ontology/go.obo

term_browser: ontobee
example_terms:
- GO_0000001

entries:
- exact: /go.obo
  replacement: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/go.obo

- exact: /go.owl
  replacement: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/go.owl

- exact: /tracker
  replacement: https://github.com/geneontology/go-ontology/issues

- prefix: /experimental/
  replacement: http://geneontology.org/experimental/

## the noctua ontology does not fit in the main GO SVN space, use a Jenkins artefact for now
## see https://github.com/geneontology/neo/issues/5
- prefix: /noctua/
  replacement: https://build.berkeleybop.org/job/build-noctua-entity-ontology/lastSuccessfulBuild/artifact/

- prefix: /releases/
  replacement: http://viewvc.geneontology.org/viewvc/GO-SVN/ontology-releases/

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=GO&iri=http://purl.obolibrary.org/obo/

- prefix: /
  replacement: http://geneontology.org/ontology/

