# PURL configuration for http://purl.obolibrary.org/obo/hp

idspace: HP
base_url: /obo/hp

products:
- hp.owl: https://compbio.charite.de/jenkins/job/hpo/lastStableBuild/artifact/hp/hp.owl
- hp.obo: https://compbio.charite.de/jenkins/job/hpo/lastStableBuild/artifact/hp/hp.obo

term_browser: ontobee
example_terms:
- HP_0000001

entries:
- prefix: /uberpheno/
  replacement: http://compbio.charite.de/hudson/job/hpo.ontology.uberpheno/lastStableBuild/artifact/data/uberphenoOut/

- prefix: /releases/
  replacement: https://compbio.charite.de/svn/hpo/releases/

- prefix: /tracker
  replacement: https://github.com/obophenotype/human-phenotype-ontology/issues

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=HP&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/HP_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=HP&iri=http://purl.obolibrary.org/obo/HP_0000001

- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/src/ontology/

