# PURL configuration for http://purl.obolibrary.org/obo/hsapdv

idspace: HsapDv
base_url: /obo/hsapdv

products:
- hsapdv.owl: https://github.com/obophenotype/developmental-stage-ontologies/releases/latest/download/hsapdv.owl
- hsapdv.obo: https://github.com/obophenotype/developmental-stage-ontologies/releases/latest/download/hsapdv.obo
- hsapdv.json: https://github.com/obophenotype/developmental-stage-ontologies/releases/latest/download/hsapdv.json

term_browser: ontobee
example_terms:
- HsapDv_0000000
