# PURL configuration for http://purl.obolibrary.org/obo/idomal

idspace: IDOMAL
base_url: /obo/idomal

products:
- idomal.owl: http://ontologies.berkeleybop.org/idomal.owl

term_browser: ontobee
example_terms:
- IDOMAL_0000000
