# PURL configuration for http://purl.obolibrary.org/obo/mmusdv

idspace: MmusDv
base_url: /obo/mmusdv

products:
- mmusdv.owl: https://github.com/obophenotype/developmental-stage-ontologies/releases/latest/download/mmusdv.owl
- mmusdv.obo: https://github.com/obophenotype/developmental-stage-ontologies/releases/latest/download/mmusdv.obo
- mmusdv.json: https://github.com/obophenotype/developmental-stage-ontologies/releases/latest/download/mmusdv.json

term_browser: ontobee
example_terms:
- MmusDv_0000000
