# PURL configuration for http://purl.obolibrary.org/obo/mod

idspace: MOD
base_url: /obo/mod

products:
- mod.owl: http://ontologies.berkeleybop.org/mod.owl

term_browser: ontobee
example_terms:
- MOD_00000
