# PURL configuration for http://purl.obolibrary.org/obo/mp

idspace: MP
base_url: /obo/mp

products:
- mp.owl: http://ontologies.berkeleybop.org/mp.owl
- mp.obo: http://ontologies.berkeleybop.org/mp.obo

term_browser: ontobee
example_terms:
- MP_0000001

entries:
- prefix: /about/
  replacement: http://www.ebi.ac.uk/ontology-lookup/browse.do?ontName=MP&termId=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/MP_0000001
    to: http://www.ebi.ac.uk/ontology-lookup/browse.do?ontName=MP&termId=http://purl.obolibrary.org/obo/MP_0000001

- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/mammalian-phenotype-ontology/master/src/ontology/

