# PURL configuration for http://purl.obolibrary.org/obo/mpath

idspace: MPATH
base_url: /obo/mpath

products:
- mpath.owl: http://ontologies.berkeleybop.org/mpath.owl
- mpath.obo: http://ontologies.berkeleybop.org/mpath.obo

term_browser: ontobee
example_terms:
- MPATH_1
