# PURL configuration for http://purl.obolibrary.org/obo/mpath

idspace: MPATH
base_url: /obo/mpath

products:
- mpath.obo: https://raw.githubusercontent.com/PaulNSchofield/mpath/master/mpath.obo

term_browser: ontobee
example_terms:
- MPATH_1
