# PURL configuration for http://purl.obolibrary.org/obo/ms

idspace: MS
base_url: /obo/ms

products:
- ms.owl: https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.owl
- ms.obo: https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo

term_browser: ontobee

example_terms:
- MS_0000000

entries:
- regex: /releases/v?(\d+\.\d+\.\d+)
  replacement: https://github.com/HUPO-PSI/psi-ms-CV/releases/download/v$1/psi-ms.obo

- exact: /tracker
  replacement: https://github.com/HUPO-PSI/psi-ms-CV/issues

- prefix: /about/
  replacement: https://psidev.info/groups/controlled-vocabularies

- prefix: /
  replacement: https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/

