# PURL configuration for http://purl.obolibrary.org/obo/ms

idspace: MS
base_url: /obo/ms

products:
- ms.owl: https://github.com/HUPO-PSI/psi-ms-CV/releases/latest/download/ms.owl
- ms.obo: https://github.com/HUPO-PSI/psi-ms-CV/releases/latest/download/psi-ms.obo

term_browser: ontobee

example_terms:
- MS_0000000

entries:
- exact: /tracker
  replacement: https://github.com/HUPO-PSI/psi-ms-CV/issues

# intercept exact matches before version prefix blindly grabs everything
- exact: /ms.owl
  replacement: https://github.com/HUPO-PSI/psi-ms-CV/releases/latest/download/ms.owl
- exact: /psi-ms.owl
  replacement: https://github.com/HUPO-PSI/psi-ms-CV/releases/latest/download/psi-ms.owl
- exact: /ms.obo
  replacement: https://github.com/HUPO-PSI/psi-ms-CV/releases/latest/download/psi-ms.obo
- exact: /psi-ms.obo
  replacement: https://github.com/HUPO-PSI/psi-ms-CV/releases/latest/download/psi-ms.obo


- prefix: /about/
  replacement: https://psidev.info/groups/controlled-vocabularies

- prefix: /home
  replacement: https://github.com/HUPO-PSI/psi-ms-CV

# preserve prior PURLs
- prefix: /releases/
  replacement: https://github.com/HUPO-PSI/psi-ms-CV/releases/download/v
  tests:
    - from: /4.1.186/ms.owl
      to: https://github.com/HUPO-PSI/psi-ms-CV/releases/download/v4.1.186/ms.owl
    - from: /4.1.186/psi-ms.obo
      to: https://github.com/HUPO-PSI/psi-ms-CV/releases/download/v4.1.186/psi-ms.obo

# support directly resolving versioned IRIs
- prefix: /
  replacement: https://github.com/HUPO-PSI/psi-ms-CV/releases/download/v
  tests:
    - from: /4.1.186/ms.owl
      to: https://github.com/HUPO-PSI/psi-ms-CV/releases/download/v4.1.186/ms.owl
    - from: /4.1.186/psi-ms.obo
      to: https://github.com/HUPO-PSI/psi-ms-CV/releases/download/v4.1.186/psi-ms.obo
