# PURL configuration for OArCS 

idspace: OARCS
base_url: /aszool/oarcs

products:
- oarcs.owl: https://github.com/aszool/oarcs/src/ontology/oarcs.owl

term_browser: custom

entries:
- exact: /wiki
  replacement: https://github.com/aszool/oarcs/wiki

- exact: /browse
  replacement: http://www.ontobee.org/browser/index.php?o=OARCS

