# PURL configuration for http://purl.obolibrary.org/obo/

idspace: OBO
base_url: /obo

term_browser: custom


### Global Tests
tests:
# Test case insensitivity
- from: /chebi/about/CHEBI_15377
  to: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI_15377
- from: /CHEBI/about/CHEBI_15377
  to: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI_15377


### Entries
entries:


### Term Overrides

- exact: /BFO_0000050
  replacement: http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/BFO_0000050

- exact: /BFO_0000051
  replacement: http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/BFO_0000051

- exact: /BFO_0000066
  replacement: http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/BFO_0000066

- exact: /BFO_0000062
  replacement: http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/BFO_0000062


### Custom (non-Ontobee) term_browser redirects

# Term redirects for CHEBI
- regex: ^/obo/CHEBI_(\d+)$
  replacement: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:$1
  status: see other
  tests:
  - from: /CHEBI_15377
    to: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:15377

# Term redirects for HAO
- regex: ^/obo/HAO_(\d+)$
  replacement: http://api.hymao.org/api/ontology/ontology_class/HAO_$1
  status: see other
  tests:
  - from: /HAO_0000000
    to: http://api.hymao.org/api/ontology/ontology_class/HAO_0000000

# Term redirects for PR
# Match digits or UniProt ID, see http://www.uniprot.org/help/accession_numbers
- regex: ^/obo/PR_(\d+|[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2})$
  replacement: http://pir.georgetown.edu/cgi-bin/pro/entry_pro?id=PR_$1
  status: see other
  tests:
  - from: /PR_000000001
    to: http://pir.georgetown.edu/cgi-bin/pro/entry_pro?id=PR_000000001
  - from: /PR_Q9BWV1
    to: http://pir.georgetown.edu/cgi-bin/pro/entry_pro?id=PR_Q9BWV1


### OBO Format Specification
- exact: /oboformat/
  replacement: http://owlcollab.github.io/oboformat/doc/obo-syntax.html

- exact: /oboformat/spec.html
  replacement: http://owlcollab.github.io/oboformat/doc/obo-syntax.html
