# PURL configuration for http://purl.obolibrary.org/obo/omrse

idspace: OMRSE
base_url: /obo/omrse

products:
- omrse.owl: https://raw.githubusercontent.com/ufbmi/OMRSE/master/omrse/omrse.owl

term_browser: ontobee
example_terms:
- OMRSE_00000098

entries:

- exact: /dev/omrse.owl
  replacement: https://raw.githubusercontent.com/ufbmi/OMRSE/devel/omrse.owl

- exact: /dao.owl
  replacement: https://raw.githubusercontent.com/ufbmi/demo-app-ontology/master/DAO.owl
