# PURL configuration for http://purl.obolibrary.org/obo/sepio

idspace: SEPIO
base_url: /obo/sepio

products:
- sepio.owl: https://raw.githubusercontent.com/monarch-initiative/SEPIO-ontology/master/sepio.owl

term_browser: ontobee
example_terms:
- SEPIO_0000001

entries:

- exact: /bfo-mireot.owl
  replacement: https://raw.githubusercontent.com/monarch-initiative/SEPIO-ontology/master/src/ontology/mireots/bfo-mireot.owl

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/monarch-initiative/SEPIO-ontology/v

- prefix: /tracker/
  replacement: https://github.com/monarch-initiative/SEPIO-ontology/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/SEPIO?iri=http://purl.obolibrary.org/obo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/monarch-initiative/master/SEPIO-ontology/
