# PURL configuration for http://purl.obolibrary.org/obo/tads

idspace: TADS
base_url: /obo/tads

products:
- tads.owl: http://ontologies.berkeleybop.org/tads.owl
- tads.obo: http://ontologies.berkeleybop.org/tads.obo

term_browser: ontobee
example_terms:
- TADS_0000000
