# PURL configuration for http://purl.obolibrary.org/obo/tgma

idspace: TGMA
base_url: /obo/tgma

products:
- tgma.owl: http://ontologies.berkeleybop.org/tgma.owl
- tgma.obo: http://ontologies.berkeleybop.org/tgma.obo

term_browser: ontobee
example_terms:
- TGMA_0000000
