# PURL configuration for http://purl.obolibrary.org/obo/trans

idspace: TRANS
base_url: /obo/trans

base_redirect: https://github.com/DiseaseOntology/PathogenTransmissionOntology/tree/master/src/ontology

products:
- trans.owl: https://raw.githubusercontent.com/DiseaseOntology/PathogenTransmissionOntology/master/src/ontology/trans.owl
- trans.obo: https://raw.githubusercontent.com/DiseaseOntology/PathogenTransmissionOntology/master/src/ontology/transmission_process.obo

term_browser: ontobee
example_terms:
- TRANS_0000000
