# PURL configuration for http://purl.obolibrary.org/obo/uo

idspace: UO
base_url: /obo/uo

products:
- uo.owl: http://ontologies.berkeleybop.org/uo.owl
- uo.obo: http://ontologies.berkeleybop.org/uo.obo

term_browser: ontobee
example_terms:
- UO_0000000
