# PURL configuration for http://purl.obolibrary.org/obo/vt

idspace: VT
base_url: /obo/vt

products:
- vt.owl: https://raw.githubusercontent.com/obophenotype/upheno/master/vt/vt.owl
- vt.obo: https://raw.githubusercontent.com/obophenotype/upheno/master/vt/vt.obo

term_browser: ontobee
example_terms:
- VT_0000001

entries:
- prefix: /avout/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OBA&iri=http://purl.obolibrary.org/obo/

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OBA&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/VT_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=OBA&iri=http://purl.obolibrary.org/obo/VT_0000001
