# PURL configuration for http://purl.obolibrary.org/obo/wbbt

idspace: WBbt
base_url: /obo/wbbt

products:
- wbbt.owl: http://ontologies.berkeleybop.org/wbbt.owl
- wbbt.obo: http://ontologies.berkeleybop.org/wbbt.obo

term_browser: ontobee
example_terms:
- WBbt_0005733
