# PURL configuration for http://purl.obolibrary.org/obo/wbls

idspace: WBls
base_url: /obo/wbls

products:
- wbls.owl: http://ontologies.berkeleybop.org/wbls.owl
- wbls.obo: http://ontologies.berkeleybop.org/wbls.obo

term_browser: ontobee
example_terms:
- WBls_0000075
