####
#### WARNING: WIP
#### This playbook is for ??.??.
####  * Add remote logging to an already established server on S3.
####
---
- hosts: all
  remote_user: ubuntu
  become: yes
  roles:
    - role: logrotate-to-s3
      var_s3_path: "obo/purl"
      var_name_prefix: ""
      var_s3_push_credentials: "/home/sjcarbon/local/share/secrets/bbop/aws/s3/.s3cfg.go-push"
      target_service: "apache2"
